
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace contactosProyecto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contact
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Number { get; set; }

    public bool Favorite { get; set; }

    public bool Emergency { get; set; }

    public string Detail { get; set; }

}

}
