

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace contactosProyecto.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PhonebookEntities : DbContext
{
    public PhonebookEntities()
        : base("name=PhonebookEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Contact> Contacts { get; set; }

}

}

